@startuml
'https://plantuml.com/class-diagram

class main
class json_input

main -> json_input

class main{
String input
}

class json_input{
compare (input <-> JSON file)
output

}


@enduml