@startuml
'https://plantuml.com/class-diagram

class main
class input
class output

input -|> main
main -|> output

class input {
File "exercise41.txt"
ArrayList<String> List
}

class output{
ArrayList size()
Array print
}

class main{
ArrayList<String>
}

@enduml